# Generated by Django 4.1.5 on 2023-04-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_name_en_us_category_name_ru_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoryType_en_us',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType_ru',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
    ]
